require("user.globals")
require("user.options")
require("user.plugins")
require("user.impatient")
require("user.whichkey")
require("user.keymaps")
require("user.autocommands")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.illuminate")
require("user.indentline")
require("user.alpha")
require("user.lsp")
require("user.dap")
require("user.bookmarks")
require("user.null-ls")
require("user.numb")
require("user.neoscroll")
require("user.dressing")
require("user.legendary")
require("user.trouble")
require("user.rusttools")
-- require("user.aerial")
require("user.ide")
require("user.obsidian")
require("user.symbols_outline")
-- require("mason").setup() ]]
-- require("neoscroll").setup()
require("hop").setup({ keys = "etovxqpdygfblzhckisuran" })
